[package]
name = "qinode-graph"
version.workspace = true
edition.workspace = true

[dependencies]
async-graphql = "7"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
tokio-stream = { version = "0.1", features = ["sync"] }
uuid = { version = "1", features = ["v4"] }
