groups:
  - name: qinode
    rules:
      - alert: ClickHouseDown
        expr: up{job="clickhouse"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: ClickHouse scrape down
